#!/usr/bin/env python

import csv
import os
from shutil import copyfile

from jinja2 import Environment, FileSystemLoader


def get_books(path):
    if not os.path.exists(path):
        return
    f = open(path)
    reader = csv.DictReader(f)
    return list(reader)


def render(values):
    env = Environment(loader=FileSystemLoader('themes/default'))
    template = env.get_template('index.html')
    return template.render(values)


def ensure_build_directory(path):
    if os.path.exists(path):
        return
    os.mkdir(path)


def write_file(path, contents):
    with open(path, 'w') as f:
        f.write(contents)


def copy_css(path):
    copyfile('themes/default/style.css', path + '/style.css')


def main():
    path = 'books.csv'
    results = get_books(path)
    if not results:
        print("Couldn't get books")
        return

    ensure_build_directory('build')
    values = {
        'books': results
    }

    html = render(values)
    write_file('build/index.html', html)
    copy_css('build')


if __name__ == '__main__':
    main()
