#!/usr/bin/env python

import csv
import os

def get_books(path):
    if not os.path.exists(path):
        return
    f = open(path)
    reader = csv.DictReader(f)
    return list(reader)


def main():
    path = 'books.csv'
    results = get_books(path)
    if not results:
        print("Couldn't get books")
        return

    print(results)


if __name__ == '__main__':
    main()
